// <auto-generated />
using System;
using DevHubSync.BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHubSync.BlazorApp.Migrations
{
    [DbContext(typeof(DevHubSyncDbContext))]
    partial class DevHubSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.DevOpsProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("OrganizationUrl", "ProjectId")
                        .IsUnique();

                    b.ToTable("DevOpsProjects");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.GitHubUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("GitHubUsers");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.RepositoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevOpsProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Forks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GitHubUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevOpsProjectId");

                    b.HasIndex("GitHubUserId");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.SyncLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncOperationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncOperationId");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.SyncOperationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceRepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("SourceRepositoryId");

                    b.HasIndex("TargetRepositoryId");

                    b.ToTable("SyncOperations");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.RepositoryEntity", b =>
                {
                    b.HasOne("DevHubSync.BlazorApp.Data.Entities.DevOpsProject", "DevOpsProject")
                        .WithMany("Repositories")
                        .HasForeignKey("DevOpsProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevHubSync.BlazorApp.Data.Entities.GitHubUser", "GitHubUser")
                        .WithMany("Repositories")
                        .HasForeignKey("GitHubUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DevOpsProject");

                    b.Navigation("GitHubUser");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.SyncLogEntity", b =>
                {
                    b.HasOne("DevHubSync.BlazorApp.Data.Entities.SyncOperationEntity", "SyncOperation")
                        .WithMany("Logs")
                        .HasForeignKey("SyncOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncOperation");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.SyncOperationEntity", b =>
                {
                    b.HasOne("DevHubSync.BlazorApp.Data.Entities.RepositoryEntity", "SourceRepository")
                        .WithMany("SourceSyncOperations")
                        .HasForeignKey("SourceRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevHubSync.BlazorApp.Data.Entities.RepositoryEntity", "TargetRepository")
                        .WithMany("TargetSyncOperations")
                        .HasForeignKey("TargetRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceRepository");

                    b.Navigation("TargetRepository");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.DevOpsProject", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.GitHubUser", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.RepositoryEntity", b =>
                {
                    b.Navigation("SourceSyncOperations");

                    b.Navigation("TargetSyncOperations");
                });

            modelBuilder.Entity("DevHubSync.BlazorApp.Data.Entities.SyncOperationEntity", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
