
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async githubStartDeviceFlow(scopes: string[]) : Promise<Result<DeviceFlowResponse, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_start_device_flow", { scopes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubPollAuth(deviceCode: string, interval: number) : Promise<Result<AuthResult, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_poll_auth", { deviceCode, interval }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubGetAuthStatus() : Promise<Result<AuthResult, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_get_auth_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubSignOut() : Promise<Result<null, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubListUserRepos(page: number, perPage: number) : Promise<Result<RepoListResponse, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_list_user_repos", { page, perPage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubListOrgRepos(org: string, page: number, perPage: number) : Promise<Result<RepoListResponse, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_list_org_repos", { org, page, perPage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubGetRepoContents(owner: string, repo: string, path: string) : Promise<Result<ContentEntry[], GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_get_repo_contents", { owner, repo, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubGetFileContent(owner: string, repo: string, path: string) : Promise<Result<FileContent, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_get_file_content", { owner, repo, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubCreateIssue(owner: string, repo: string, title: string, body: string, labels: string[]) : Promise<Result<IssueSummary, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_create_issue", { owner, repo, title, body, labels }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubCheckRateLimit() : Promise<Result<RateLimitInfo, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_check_rate_limit") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanRepository(owner: string, repo: string) : Promise<Result<RepoHealthReport, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_repository", { owner, repo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanAllRepositories(repos: RepoSummary[]) : Promise<Result<CachedRepoHealthReport[], GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_all_repositories", { repos }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanRepositoryCached(owner: string, repo: string, defaultBranch: string) : Promise<Result<CachedRepoHealthReport, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_repository_cached", { owner, repo, defaultBranch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoDiagnostics(repoFullName: string) : Promise<Result<RepoHealthReport | null, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_diagnostics", { repoFullName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanSingleDiagnostic(owner: string, repo: string, ruleId: string) : Promise<Result<DiagnosticResult, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_single_diagnostic", { owner, repo, ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDiagnosticRules() : Promise<RuleInfo[]> {
    return await TAURI_INVOKE("list_diagnostic_rules");
},
async persistRepos(repos: RepoSummary[]) : Promise<Result<null, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("persist_repos", { repos }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCachedRepos() : Promise<Result<RepoSummary[], GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_cached_repos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadAllDiagnostics() : Promise<Result<RepoHealthReport[], GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_all_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateBacklogFromScan(reports: RepoHealthReport[]) : Promise<Result<BacklogItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_backlog_from_scan", { reports }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBacklog(filters: BacklogFilters) : Promise<Result<BacklogItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_backlog", { filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateBacklogItemStatus(id: string, status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_backlog_item_status", { id, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBacklog(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_backlog", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createGithubIssueFromBacklog(itemId: string) : Promise<Result<IssueSummary, GitHubError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_github_issue_from_backlog", { itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthResult = { authenticated: boolean; username: string | null; avatarUrl: string | null; scopes: string[] }
export type BacklogFilters = { owner: string | null; repo: string | null; severity: string | null; status: string | null; source: string | null }
export type BacklogItem = { id: string; repoFullName: string; source: string; sourceRef: string | null; title: string; description: string | null; severity: string; status: string; priorityScore: number; githubIssueUrl: string | null; createdAt: string; updatedAt: string }
export type CachedRepoHealthReport = { report: RepoHealthReport; commitSha: string; fromCache: boolean }
export type ContentEntry = { name: string; entryType: string; path: string; size: number | null }
export type DeviceFlowResponse = { deviceCode: string; userCode: string; verificationUri: string; expiresIn: number; interval: number }
export type DiagnosticResult = { ruleId: string; ruleName: string; severity: Severity; passed: boolean; message: string }
export type FileContent = { name: string; path: string; content: string; size: number }
export type GitHubError = { type: "OAuthFailed"; message: string } | { type: "AuthorizationPending" } | { type: "AccessDenied" } | { type: "ExpiredToken" } | { type: "SlowDown" } | { type: "KeychainError"; message: string } | { type: "NetworkError"; message: string } | { type: "NotAuthenticated" } | { type: "RateLimitExceeded"; message: string } | { type: "Internal"; message: string } | { type: "Cancelled" } | { type: "ApiError"; message: string } | { type: "NotFound"; message: string } | { type: "Forbidden"; message: string } | { type: "MergeNotAllowed"; message: string } | { type: "HeadChanged"; message: string } | { type: "ValidationFailed"; message: string }
export type IssueSummary = { number: number; title: string; state: string; htmlUrl: string }
export type RateLimitInfo = { limit: number; remaining: number; reset: number; used: number }
export type RepoHealthReport = { repoFullName: string; owner: string; repoName: string; healthScore: number; criticalCount: number; warningCount: number; infoCount: number; results: DiagnosticResult[]; scannedAt: string }
export type RepoListResponse = { items: RepoSummary[]; hasNextPage: boolean; nextPage: number | null }
export type RepoSummary = { fullName: string; owner: string; name: string; description: string | null; defaultBranch: string; topics: string[]; isArchived: boolean; isPrivate: boolean; hasIssues: boolean; openIssuesCount: number; pushedAt: string | null; htmlUrl: string; licenseName: string | null }
export type RuleInfo = { id: string; name: string; severity: Severity }
export type Severity = "critical" | "warning" | "info"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
